name: Build, test and push image

on:
  push:
    branches: [main]
    paths:
      - "8.4"
      - "8.3"
      - "8.2"
      - "8.1"
      - "8.0"
      - "7.4"
      - "7.2"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Test image
        run: |-
          make test-all

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Log in to GHCR
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |-
          make release-all

      - name: Push image to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        run: |-
          make release-all-to-ghcr
